// Generated by CoffeeScript 1.9.1
(function() {
  var logger, pm25in, serviceManager, util, weathercn;

  util = require('util');

  weathercn = require('./weathercn/weathercnService');

  pm25in = require('./pm25in/pm25inService');

  logger = require('../models/logger.server.model');

  exports.serviceManager = serviceManager = {};

  serviceManager.register = function() {
    var pm25inService, weatherService;
    logger.info("注册服务", {
      'action': 'register',
      'source': logger.source.serviceManager
    });
    this.services = {};
    weatherService = new weathercn.WeathercnService;
    this.services['weathercn'] = weatherService;
    pm25inService = new pm25in.Pm25inService;
    return this.services['pm25in'] = pm25inService;
  };

  serviceManager.init = function() {
    var k, ref, results, v;
    this.register();
    logger.info("初始化服务", {
      'action': 'init',
      'source': logger.source.serviceManager
    });
    ref = this.services;
    results = [];
    for (k in ref) {
      v = ref[k];
      results.push(v.init());
    }
    return results;
  };

  serviceManager.run = function() {
    var k, ref, results, v;
    this.init();
    logger.info("运行服务", {
      'action': 'run',
      'source': logger.source.serviceManager
    });
    ref = this.services;
    results = [];
    for (k in ref) {
      v = ref[k];
      results.push(v.run());
    }
    return results;
  };

  serviceManager.getService = function(name) {
    return this.services[name];
  };

}).call(this);
